# version: 2

build:
  image: testing

# formats: [pdf]
sphinx:
  configuration: docs/source/conf.py

python:
  version: 3.9
  install:
    - method: pip
      path: .
      extra_requirements: [doc]
