[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.semantic_release]

branch =  "main"
version_variable = "version.toml:__version__"

build_command = ""
remove_dist = false
upload_to_release = false

major_on_zero = false
upload_to_pypi = false
check_build_status = false

commit_subject = ":memo: build(version): Bump to version - {version}."
